import assert from "node:assert/strict";
import { cp, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { checkAgentProfiles, parseStrictYaml } from "./checker.mjs";
const ROOT = fileURLToPath(new URL("../..", import.meta.url));
test("canonical single Main Skill passes", async () => { const result = await checkAgentProfiles(ROOT); assert.equal(result.ok, true, result.diagnostics.map((item) => `${item.code}: ${item.reason}`).join("\n")); assert.deepEqual(result.summary, { skills: 1, roles: 4, mainResources: 4 }); });
test("strict YAML rejects aliases and duplicate keys", () => { assert.throws(() => parseStrictYaml("a: &x [one]\nb: *x\n"), /aliases/); assert.throws(() => parseStrictYaml("a: one\na: two\n")); });
test("deleted role Skill is rejected", async () => { const temp = await mkdtemp(path.join(os.tmpdir(), "oet-check-")); try { await cp(path.join(ROOT, ".agents"), path.join(temp, ".agents"), { recursive: true }); const old = path.join(temp, ".agents/skills/develop-work-item"); await cp(path.join(ROOT, ".agents/skills/orchestrate-engineering-team"), old, { recursive: true }); await writeFile(path.join(old, "SKILL.md"), "---\nname: develop-work-item\n---\n"); const result = await checkAgentProfiles(temp); assert.equal(result.ok, false); assert.ok(result.diagnostics.some((item) => item.code === "OLD_PUBLIC_SKILL")); } finally { await rm(temp, { recursive: true, force: true }); } });
